// SPDX-License-Identifier: Apache-2.0

+incdir+ibex/rtl
+incdir+ibex/vendor/lowrisc_ip/ip/prim/rtl
+incdir+ibex/vendor/lowrisc_ip/dv/sv/dv_utils
+define+SYNTHESIS
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_cipher_pkg.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi_pkg.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_pkg.sv
ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_buf.sv
ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_clock_gating.sv
ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_flop.sv
ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_flop_2sync.sv
ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_flop_en.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_sec_anchor_buf.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_sparse_fsm_flop.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_lfsr.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
ibex/rtl/ibex_pkg.sv
ibex/rtl/ibex_alu.sv
ibex/rtl/ibex_branch_predict.sv
ibex/rtl/ibex_compressed_decoder.sv
ibex/rtl/ibex_controller.sv
ibex/rtl/ibex_cs_registers.sv
ibex/rtl/ibex_csr.sv
ibex/rtl/ibex_counter.sv
ibex/rtl/ibex_decoder.sv
ibex/rtl/ibex_ex_block.sv
ibex/rtl/ibex_fetch_fifo.sv
ibex/rtl/ibex_id_stage.sv
ibex/rtl/ibex_if_stage.sv
ibex/rtl/ibex_load_store_unit.sv
ibex/rtl/ibex_multdiv_fast.sv
ibex/rtl/ibex_multdiv_slow.sv
ibex/rtl/ibex_prefetch_buffer.sv
ibex/rtl/ibex_pmp.sv
ibex/rtl/ibex_wb_stage.sv
ibex/rtl/ibex_dummy_instr.sv
ibex/rtl/ibex_icache.sv
ibex/rtl/ibex_core.sv
