// SPDX-License-Identifier: Apache-2.0

+incdir+opentitan/hw/ip/aes/rtl
+incdir+opentitan/hw/ip/prim/rtl
+define+SYNTHESIS
opentitan/hw/ip/prim/rtl/prim_util_pkg.sv
opentitan/hw/ip/prim/rtl/prim_cipher_pkg.sv
opentitan/hw/ip/prim/rtl/prim_mubi_pkg.sv
opentitan/hw/ip/prim/rtl/prim_trivium_pkg.sv
opentitan/hw/ip/entropy_src/rtl/entropy_src_pkg.sv
opentitan/hw/ip/csrng/rtl/csrng_reg_pkg.sv
opentitan/hw/ip/csrng/rtl/csrng_pkg.sv
opentitan/hw/ip/edn/rtl/edn_pkg.sv
opentitan/hw/ip/aes/rtl/aes_reg_pkg.sv
opentitan/hw/ip/aes/rtl/aes_sbox_canright_pkg.sv
opentitan/hw/ip/aes/rtl/aes_pkg.sv
opentitan/hw/ip/prim_generic/rtl/prim_and2.sv
opentitan/hw/ip/prim_generic/rtl/prim_buf.sv
opentitan/hw/ip/prim_generic/rtl/prim_flop.sv
opentitan/hw/ip/prim_generic/rtl/prim_flop_en.sv
opentitan/hw/ip/prim_generic/rtl/prim_xor2.sv
opentitan/hw/ip/prim/rtl/prim_sec_anchor_buf.sv
opentitan/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv
opentitan/hw/ip/prim/rtl/prim_dom_and_2share.sv
opentitan/hw/ip/prim/rtl/prim_trivium.sv
opentitan/hw/ip/aes/rtl/aes_sel_buf_chk.sv
opentitan/hw/ip/aes/rtl/aes_sbox_lut.sv
opentitan/hw/ip/aes/rtl/aes_sbox_canright.sv
opentitan/hw/ip/aes/rtl/aes_sbox_canright_masked_noreuse.sv
opentitan/hw/ip/aes/rtl/aes_sbox_canright_masked.sv
opentitan/hw/ip/aes/rtl/aes_sbox_dom.sv
opentitan/hw/ip/aes/rtl/aes_sbox.sv
opentitan/hw/ip/aes/rtl/aes_sub_bytes.sv
opentitan/hw/ip/aes/rtl/aes_shift_rows.sv
opentitan/hw/ip/aes/rtl/aes_mix_single_column.sv
opentitan/hw/ip/aes/rtl/aes_mix_columns.sv
opentitan/hw/ip/aes/rtl/aes_key_expand.sv
opentitan/hw/ip/aes/rtl/aes_prng_masking.sv
opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm.sv
opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm_p.sv
opentitan/hw/ip/aes/rtl/aes_cipher_control_fsm_n.sv
opentitan/hw/ip/aes/rtl/aes_cipher_control.sv
opentitan/hw/ip/aes/rtl/aes_cipher_core.sv
